/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DotoliStaking } from "./DotoliStaking";

export { DotoliStaking__factory } from "./factories/DotoliStaking__factory";
