/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DotoliInfo } from "./DotoliInfo";

export { DotoliInfo__factory } from "./factories/DotoliInfo__factory";
